### ISSUE TITLE
`npm ls` complains of extraneous modules

### ISSUE THREAD

**Issue by iarna** [aredridel/node-bin#2]
The platform specific module is not in any package.json and so is always gonna be extraneous.

This could be fixed by ditching the `preinstall` and instead using `optionalDepencies` w/ all of the platforms, pinned to the matching version and with those platform specific modules having `cpu` and `os` `package.json` restrictions https://docs.npmjs.com/files/package.json#os

This would have the bonus effect of making this work on Windows.

**Comment by aredridel** [comment]
That sounds like a great way to go! I was just thinking about that yesterday.

**Comment by iarna** [comment]
I think this can be called complete with the release of `node-bin@4`!
